# Generated by Django 5.2.7 on 2025-10-31 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_initial'),
        ('hospital', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='health_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='worker.healthworker'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.hospital'),
        ),
    ]
