# Generated by Django 5.2.7 on 2025-10-31 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
    ]
