# Generated by Django 5.2.7 on 2025-11-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('health_worker', 'Health Worker'), ('super_admin', 'Super Admin')], default='super_admin', max_length=20),
        ),
    ]
