# Generated by Django 5.2.7 on 2025-10-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('doctor', 'Doctor'), ('health_worker', 'Health Worker')], default='health_worker', max_length=20),
        ),
    ]
