# Generated by Django 5.2.7 on 2025-11-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_user_notification_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
