# Generated by Django 5.2.7 on 2025-11-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_health_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='health_worker',
        ),
    ]
