# Generated by Django 5.2.7 on 2025-11-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_created_by'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='health_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='worker.healthworker'),
        ),
    ]
